// Deploy-time database helper (used by Render, works anywhere).
//
// Picks the correct Prisma schema twin from DATABASE_URL, so the same
// buildCommand serves SQLite local dev and Postgres production:
//
//   node scripts/render-db.js push           # copy twin -> schema.prisma, generate, db push
//   node scripts/render-db.js seed-if-empty  # seed only when the demo org is absent
//
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const prismaDir = path.join(__dirname, "..", "prisma");
const active = path.join(prismaDir, "schema.prisma");
const twins = {
  sqlite: path.join(prismaDir, "schema.sqlite.prisma"),
  postgres: path.join(prismaDir, "schema.postgres.prisma"),
};

function detectDialect() {
  const url = process.env.DATABASE_URL || "";
  if (url.startsWith("file:")) return "sqlite";
  if (url.startsWith("postgres")) return "postgres";
  // No DATABASE_URL (e.g. bare local build): fall back to whatever twin is
  // already active, preferring the zero-config SQLite twin.
  if (fs.existsSync(active)) {
    const text = fs.readFileSync(active, "utf8");
    if (/provider\s*=\s*"sqlite"/.test(text)) return "sqlite";
    if (/provider\s*=\s*"postgres"/.test(text)) return "postgres";
  }
  return "sqlite";
}

function activate(dialect) {
  const twin = twins[dialect];
  if (!fs.existsSync(twin)) {
    console.error(`[render-db] missing twin schema: ${twin}`);
    process.exit(1);
  }
  fs.copyFileSync(twin, active);
  console.log(`[render-db] DATABASE_URL=${dialect} -> schema.prisma (${path.basename(twin)})`);
}

function run(cmd) {
  console.log(`[render-db] $ ${cmd}`);
  execSync(cmd, { stdio: "inherit" });
}

const [, , cmd] = process.argv;

try {
  if (cmd === "generate") {
    // postinstall: activate the right twin before generating the client.
    const dialect = detectDialect();
    activate(dialect);
    run("npx prisma generate");
  } else if (cmd === "push") {
    const dialect = detectDialect();
    activate(dialect);
    run("npx prisma generate");
    run("npx prisma db push --skip-generate");
  } else if (cmd === "seed-if-empty") {
    // Runtime step: schema.prisma is already active and the client already
    // generated by the build (push), so no dialect switch or generate here.
    // No pre-check either: the seed script is fully idempotent (upserts +
    // DEMO-origin guard), so running it on every boot is safe and self-guarding.
    run("npx tsx prisma/seed.ts");
  } else {
    console.error("usage: node scripts/render-db.js [push|seed-if-empty]");
    process.exit(1);
  }
} catch (err) {
  console.error("[render-db] failed:", err.message);
  process.exit(1);
}
